### ISSUE TITLE
Where to set the port?

### ISSUE THREAD

**Issue by JakeFishcode** [panagelak/rq_fts_ros2_driver#2]
It's nice to have a interface in ros2 controls.
Thanks for your jobs,helps me a lot.
But I can't found the port for ft.suck like USB1 or USB2?

**Comment by JakeFishcode** [comment]
I find that

**Comment by panagelak** [comment]
Hello @JakeFishcode 

Yes the documentation is not very clear for this, but if you want to set a specific usb port, you should set the ftdi_id to "ttyUSBx" (which for me was changing upon system restarts) and you might need to add access to the dialout group.

If it is empty it will automatically search for the port that the device is connected to, but in this case when used together with the robotiq gripper ros2 control, it was causing a crush.

**Comment by JakeFishcode** [comment]
Thanks a lot. I know how to do that now.
